import time
import rainbowhat as microcontroller

def display_countdown():
  microcontroller.display.print_str('AHOY')
  microcontroller.display.show()
  time.sleep(1)
  microcontroller.display.print_str('9')
  microcontroller.display.show()
  time.sleep(1)
  microcontroller.display.print_str('8')
  microcontroller.display.show()
  time.sleep(1)
  microcontroller.display.print_str('7')
  microcontroller.display.show()
  time.sleep(1)
  microcontroller.display.print_str('6')
  microcontroller.display.show()
  time.sleep(1)
  microcontroller.display.print_str('5')
  microcontroller.display.show()
  microcontroller.rainbow.clear()
  microcontroller.rainbow.set_pixel(1, 255, 0, 0)
  time.sleep(1)
  microcontroller.rainbow.show()
  microcontroller.rainbow.set_pixel(2, 255, 0, 0)
  time.sleep(1)
  microcontroller.rainbow.show()
  microcontroller.rainbow.set_pixel(3, 255, 0, 0)
  time.sleep(1)
  microcontroller.rainbow.show()
  microcontroller.rainbow.set_pixel(4, 255, 0, 0)
  time.sleep(1)
  microcontroller.rainbow.show()
  microcontroller.rainbow.set_pixel(5, 255, 0, 0)
  time.sleep(1)
  microcontroller.rainbow.show()
  microcontroller.rainbow.set_pixel(6, 255, 0, 0)
  microcontroller.rainbow.show()


display_countdown()